

FROM python:3.8.5

RUN useradd -ms /bin/sh admin
COPY --chown=admin:admin . /fuzzylearn
 
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1
ENV username = $username
ENV password = $password
ENV gitusername = $gitusername
ENV gitpassword = $gitpassword
ENV POETRY_VERSION=1.5.1


RUN apt-get update
RUN apt-get install -y --no-install-recommends         gnumeric 
RUN apt-get install -y --no-install-recommends python3-pip


# Install and setup poetry
WORKDIR /fuzzylearn
RUN pip3 install --upgrade pip
RUN pip install "poetry==$POETRY_VERSION"
RUN poetry config virtualenvs.create false 
RUN poetry cache clear --all pypi 
RUN poetry install  --no-interaction --no-ansi

USER admin
RUN chmod +x ./run.sh

CMD ["bash", "./run.sh"]

